# Generated by Django 3.1.2 on 2021-01-19 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structuredpdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userpdfdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=500)),
                ('buyer', models.CharField(max_length=500)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoce_date', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=500)),
                ('digitalized', models.CharField(max_length=20)),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structuredpdf.userregistration')),
            ],
        ),
    ]
