# Generated by Django 3.1.2 on 2021-01-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structuredpdf', '0002_userpdfdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
