# Generated by Django 3.1.2 on 2021-01-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structuredpdf', '0003_auto_20210119_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpdfdata',
            name='f_id',
        ),
        migrations.AddField(
            model_name='userpdfdata',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
