# Generated by Django 3.1.2 on 2021-01-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structuredpdf', '0004_auto_20210119_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpdfdata',
            name='email',
        ),
        migrations.AddField(
            model_name='userpdfdata',
            name='f_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
