# Generated by Django 3.1.2 on 2021-01-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structuredpdf', '0006_auto_20210120_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpdfdata',
            name='f_id',
        ),
    ]
